// resources/js/Pages/BasePage.vue
<template>
	<div>
		<component
			:is="component.name"
			v-for="(component, index) in components"
			:key="index"
			v-bind="component.props"
		/>
	</div>
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
	name: 'BasePage',
	props: ['components'],
});
</script>

<style></style>

// resources/js/react/Pages/BasePage.js
import React from 'react';
import { Component } from '@litstackjs/litstack-react';

class BasePage extends React.Component {
	render() {
		return (
			<div>
				{this.props.components.map((component, i) => (
					<Component
						key={i}
						is={component.name}
						{...component.props}
					/>
				))}
			</div>
		);
	}
}

export default BasePage;
