// resources/js/vue3/Pages/BasePage.vue
<template>
    <div>
        <component
            v-for="(component, index) in components"
            v-bind="component.props"
            :is="component.name"
            :key="index"
        />
    </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';
import { Component } from '@litstackjs/litstack';

export default defineComponent({
    name: 'BasePage',
    props: {
        components: {
            required: true,
            type: Array as PropType<Component[]>,
        },
    },
});
</script>

// resources/js/react/Pages/BasePage.tsx
import React from 'react';
import { Component } from '@litstackjs/litstack-react';
import { Component as TComponent } from '@litstackjs/litstack';

class BasePage extends React.Component<{ components: TComponent[] }> {
	render() {
		return (
			<div>
				{this.props.components.map((component, i) => (
					<Component
						key={i}
						name={component.name}
						props={component.props}
					/>
				))}
			</div>
		);
	}
}

export default BasePage;
